// // This is the service logic we use to generate portfolio using gemini api using prompt generated by user data

// import { GoogleGenAI, Type } from "@google/genai";

// class AIService {
//   constructor() {
//     // We got a new instance from GoogleGenAI and give it our GEMINI_API_KEY so we can communicate with gemini using prompts by the code
//     this.ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
//   }

//   async generatePortfolioContent(profileData, repositories) {
//     console.log("API KEY =", process.env.GEMINI_API_KEY);
//     const safeRepos = repositories || [];
//     const safeLanguages = profileData.topLanguages || [];

//     // We give gemini cleaned data to analyze and give use the portfolio content
//     const reposSummary = safeRepos.map((r) => ({
//       name: r.name,
//       description: r.description || "",
//       language: r.language || "",
//     }));

//     const systemPrompt = `
//       You are a technical profile compiler. Generate clean, crisp portfolio text assets based on the developer source data provided.

//       Developer Data:
//       - Name: ${profileData.name || profileData.username}
//       - Bio: ${profileData.bio || ""}
//       - Readme: ${profileData.readmeContent || ""}
//       - Top Languages: ${safeLanguages.join(", ")}

//       Repositories:
//       ${JSON.stringify(reposSummary)}

//       Strict Composition Constraints:
//       1. heroTitle: Look for a role title in the Bio/Readme. If none is found, combine the top languages into a direct engineering role title (e.g., "Frontend & Mobile Developer" or "Software Engineer"). Never use vague corporate fluff.
//       2. aboutMe: Summarize the engineering focus. If Bio and Readme are completely blank, write a clean, direct 2-sentence summary detailing their focus on the explicit tech stack provided (e.g., "Software developer specializing in building clean user interfaces and mobile applications using JavaScript, Kotlin, and Python."). Do not invent hypothetical projects.
//       3. skillsSummary: Return an array containing only items verified in the Top Languages or repository language fields.
//       4. projectCaseStudies: Map every repo. For 'aiDescription', clean up the existing repository description. If the repository has no description, write a short, single-sentence technical specification stating exactly what the stack is based on the repository name and language (e.g., "A clean frontend application built with JavaScript."). Do not use guessing phrases like "This project likely involves...".
//     `;

//     try {
//       const response = await this.ai.models.generateContent({
//         model: "gemini-2.0-flash",
//         contents: systemPrompt,
//         config: {
//           responseMimeType: "application/json",
//           responseSchema: {
//             type: Type.OBJECT,
//             properties: {
//               heroTitle: { type: Type.STRING },
//               aboutMe: { type: Type.STRING },
//               skillsSummary: {
//                 type: Type.ARRAY,
//                 items: { type: Type.STRING },
//               },
//               projectCaseStudies: {
//                 type: Type.ARRAY,
//                 items: {
//                   type: Type.OBJECT,
//                   properties: {
//                     repoName: { type: Type.STRING },
//                     aiDescription: { type: Type.STRING },
//                     suggestedTags: {
//                       type: Type.ARRAY,
//                       items: { type: Type.STRING },
//                     },
//                   },
//                   required: ["repoName", "aiDescription", "suggestedTags"],
//                 },
//               },
//             },
//             required: [
//               "heroTitle",
//               "aboutMe",
//               "skillsSummary",
//               "projectCaseStudies",
//             ],
//           },
//         },
//       });

//       return JSON.parse(response.text);
//     } catch (error) {
//       console.error("❌ Gemini Content Generation Failure:", error);
//       throw error;
//     }
//   }
// }

// export default new AIService();